version: '3.6'

services:
  groupbutler:
    build:
      context: .
      dockerfile: docker/polling.Dockerfile
      args:
        # DEPS_NATIVE: $DEPS_NATIVE
        # DEPS_ROCKS: $DEPS_ROCKS
        GB_COMMIT: $GB_COMMIT
    environment:
      REDIS_HOST: redis
    volumes:
      - ./conf:/srv/app/conf
      - ./locales:/srv/app/locales
      - ./lua:/srv/app/lua
      - ./polling.lua:/srv/app/polling.lua

  redis:
    command: --save "" --appendonly no
    image: redis:alpine
    ports:
      - "6379:6379"
